### ISSUE TITLE
Mobs ignoring fake player and 'buildadmins' attacks

### ISSUE THREAD

**Issue by zellfrey** [The-Fireplace-Minecraft-Mods/Clans#51]
When a mob farm is in use all mobs are immune to damage from all modded mob killing blocks(Extra utilities: spikes, Extra utilities:mechanical user, Draconic Evolution: Mob Grinder...e.t.c)

In more detail, mobs get hit and a sound effect occurs however there is no health reduction from targeted mob.

In regards to buildadmins: All mobs ignore any interaction with a buildadmin/opped player.

Clans-1.12.2-1.2.4
GrandEconomy-1.12.2-1.0.1

Forge version :1.12.2-14.23.5.2781

**Comment by The-Fireplace** [comment]
Alright, for buildadmins, I can get that fixed. As for the mod interactions, I'd like you to try putting a mob on a magma block from vanilla minecraft and see if that actually hurts them. If it does, I know what the problem is, but not an immediate solution.

**Comment by zellfrey** [comment]
Magma block in claimed area. Mob spawned on the block, and the mob gets damaged from standing on the block

**Comment by The-Fireplace** [comment]
Alright. My guess is that the mods are internally using fake players to deal the damage, and since fake players aren't in clans but they are still considered players, they are getting prevented from dealing it. Could you give a full list of the mod blocks you've had issues with, if they aren't already mentioned in other issues?

**Comment by The-Fireplace** [comment]
Superseded by #65
